name: gino_gennai_app
description: App di Gino Gennai

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # Altre dipendenze della tua app

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true